### ISSUE TITLE
Checking that biocViews 

### ISSUE THREAD

**Issue by harpomaxx** [harpomaxx/galgoR-package#3]
```
Checking that biocViews come from the same category...     
* WARNING: Use biocViews from one category only (one of Software, ExperimentData, AnnotationData, Workflow)
```
We need to select the proper biocViews categories.

**Comment by harpomaxx** [comment]
* Checking for non-trivial biocViews...
    * ERROR: Add biocViews other than Software
See http://bioconductor.org/developers/how-to/biocViews/

**Comment by harpomaxx** [comment]
We need to set up at least 3 biocViews. Not just one

**Comment by martinguerrero89** [comment]
Done!
